dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - "export BOTO_CONFIG=/dev/null" # https://github.com/travis-ci/travis-ci/issues/7940
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
  - python get-poetry.py --preview --yes
install:
  - ~/.poetry/bin/poetry install
  - pip uninstall ecs-tool --yes
script:
  - "~/.poetry/bin/poetry run black --check ."
